  name: My First Workflow

  on:
   # Manual trigger using the workflow_dispatch event
    workflow_dispatch:
    push:
      branches:
        - main
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Check out repository
        uses: actions/checkout@v3
  
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
  
      - name: Print a message
        run: echo "Hello, world!"
